return 
{
    [1] = {
        ["children"] = {
            [1] = {
                ["children"] = {
                    [1] = {
                        ["children"] = {
                            [1] = {
                                ["children"] = {
                                },
                                ["self"] = {
                                    ["Skin"] = 0,
                                    ["UniqueID"] = "aad69bf61c91100a83fb17c0fc637858bcd3773a946a66b63715e802c7dc6a7c",
                                    ["NoLighting"] = false,
                                    ["AimPartName"] = "",
                                    ["IgnoreZ"] = false,
                                    ["AimPartUID"] = "",
                                    ["Materials"] = "",
                                    ["Name"] = "rocket2",
                                    ["LevelOfDetail"] = 0,
                                    ["NoTextureFiltering"] = false,
                                    ["PositionOffset"] = Vector(0, 0, 0),
                                    ["IsDisturbing"] = false,
                                    ["EyeAngles"] = false,
                                    ["DrawOrder"] = 0,
                                    ["TargetEntityUID"] = "",
                                    ["Alpha"] = 1,
                                    ["Material"] = "",
                                    ["Invert"] = false,
                                    ["ForceObjUrl"] = false,
                                    ["Bone"] = "head",
                                    ["Angles"] = Angle(0, 0, 0),
                                    ["AngleOffset"] = Angle(0, 0, 0),
                                    ["BoneMerge"] = false,
                                    ["Color"] = Vector(1, 1, 1),
                                    ["Position"] = Vector(48.738647460938, 34.721717834473, 0.05859375),
                                    ["ClassName"] = "model2",
                                    ["Brightness"] = 1,
                                    ["Hide"] = false,
                                    ["NoCulling"] = false,
                                    ["Scale"] = Vector(1, 1, 1),
                                    ["LegacyTransform"] = false,
                                    ["EditorExpand"] = true,
                                    ["Size"] = 2,
                                    ["ModelModifiers"] = "",
                                    ["Translucent"] = false,
                                    ["BlendMode"] = "",
                                    ["EyeTargetUID"] = "",
                                    ["Model"] = "models/acs/missiles/default.mdl",
                                },
                            },
                            [2] = {
                                ["children"] = {
                                },
                                ["self"] = {
                                    ["Skin"] = 0,
                                    ["UniqueID"] = "cc6f7e87fb24e758019c3ffe2742292f30566bfa1c84c990f4e43e9d9bba0fd9",
                                    ["NoLighting"] = false,
                                    ["AimPartName"] = "",
                                    ["IgnoreZ"] = false,
                                    ["AimPartUID"] = "",
                                    ["Materials"] = "",
                                    ["Name"] = "rocket1",
                                    ["LevelOfDetail"] = 0,
                                    ["NoTextureFiltering"] = false,
                                    ["PositionOffset"] = Vector(0, 0, 0),
                                    ["IsDisturbing"] = false,
                                    ["EyeAngles"] = false,
                                    ["DrawOrder"] = 0,
                                    ["TargetEntityUID"] = "",
                                    ["Alpha"] = 1,
                                    ["Material"] = "",
                                    ["Invert"] = false,
                                    ["ForceObjUrl"] = false,
                                    ["Bone"] = "head",
                                    ["Angles"] = Angle(0, 0, 0),
                                    ["AngleOffset"] = Angle(0, 0, 0),
                                    ["BoneMerge"] = false,
                                    ["Color"] = Vector(1, 1, 1),
                                    ["Position"] = Vector(48.738647460938, -35.953575134277, 0.05859375),
                                    ["ClassName"] = "model2",
                                    ["Brightness"] = 1,
                                    ["Hide"] = false,
                                    ["NoCulling"] = false,
                                    ["Scale"] = Vector(1, 1, 1),
                                    ["LegacyTransform"] = false,
                                    ["EditorExpand"] = true,
                                    ["Size"] = 2,
                                    ["ModelModifiers"] = "",
                                    ["Translucent"] = false,
                                    ["BlendMode"] = "",
                                    ["EyeTargetUID"] = "",
                                    ["Model"] = "models/acs/missiles/default.mdl",
                                },
                            },
                        },
                        ["self"] = {
                            ["DrawOrder"] = 0,
                            ["UniqueID"] = "8a74ed4f1a3086d430204c5ec9915ac230fc80261d610f384d940e6a28b7ff8e",
                            ["Hide"] = false,
                            ["TargetEntityUID"] = "",
                            ["EditorExpand"] = true,
                            ["OwnerName"] = "self",
                            ["IsDisturbing"] = false,
                            ["Name"] = "origin",
                            ["Duplicate"] = false,
                            ["ClassName"] = "group",
                        },
                    },
                },
                ["self"] = {
                    ["DrawOrder"] = 0,
                    ["UniqueID"] = "c63530872c60a2ca8a4fe377c5b77ba91701448ea6c67f6cdc2c204137668b01",
                    ["Hide"] = false,
                    ["TargetEntityUID"] = "",
                    ["EditorExpand"] = true,
                    ["OwnerName"] = "self",
                    ["IsDisturbing"] = false,
                    ["Name"] = "vehicleweapon",
                    ["Duplicate"] = false,
                    ["ClassName"] = "group",
                },
            },
            [2] = {
                ["children"] = {
                    [1] = {
                        ["children"] = {
                        },
                        ["self"] = {
                            ["Skin"] = 0,
                            ["UniqueID"] = "cd6f332d4ea367aa69cdc152cdc3dd5d4b7ef8fbb7dc82c8064817a656e20724",
                            ["NoLighting"] = false,
                            ["AimPartName"] = "",
                            ["IgnoreZ"] = false,
                            ["AimPartUID"] = "",
                            ["Materials"] = "",
                            ["Name"] = "",
                            ["LevelOfDetail"] = 0,
                            ["NoTextureFiltering"] = false,
                            ["PositionOffset"] = Vector(0, 0, 0),
                            ["IsDisturbing"] = false,
                            ["EyeAngles"] = false,
                            ["DrawOrder"] = 0,
                            ["TargetEntityUID"] = "",
                            ["Alpha"] = 1,
                            ["Material"] = "",
                            ["Invert"] = false,
                            ["ForceObjUrl"] = false,
                            ["Bone"] = "head",
                            ["Angles"] = Angle(90, 90, 0),
                            ["AngleOffset"] = Angle(0, 0, 0),
                            ["BoneMerge"] = false,
                            ["Color"] = Vector(1, 1, 1),
                            ["Position"] = Vector(35.999755859375, 19.485801696777, -0.384765625),
                            ["ClassName"] = "model2",
                            ["Brightness"] = 1,
                            ["Hide"] = false,
                            ["NoCulling"] = false,
                            ["Scale"] = Vector(1, 1, 1),
                            ["LegacyTransform"] = false,
                            ["EditorExpand"] = false,
                            ["Size"] = 1,
                            ["ModelModifiers"] = "",
                            ["Translucent"] = false,
                            ["BlendMode"] = "",
                            ["EyeTargetUID"] = "",
                            ["Model"] = "models/props_c17/metalladder002b.mdl",
                        },
                    },
                    [2] = {
                        ["children"] = {
                        },
                        ["self"] = {
                            ["Skin"] = 0,
                            ["UniqueID"] = "bd0dc99828b6c8e3d06fa4581426c91f6b028f11c55b3c7461ecc2537f67cd00",
                            ["NoLighting"] = false,
                            ["AimPartName"] = "",
                            ["IgnoreZ"] = false,
                            ["AimPartUID"] = "",
                            ["Materials"] = "",
                            ["Name"] = "",
                            ["LevelOfDetail"] = 0,
                            ["NoTextureFiltering"] = false,
                            ["PositionOffset"] = Vector(0, 0, 0),
                            ["IsDisturbing"] = false,
                            ["EyeAngles"] = false,
                            ["DrawOrder"] = 0,
                            ["TargetEntityUID"] = "",
                            ["Alpha"] = 1,
                            ["Material"] = "",
                            ["Invert"] = false,
                            ["ForceObjUrl"] = false,
                            ["Bone"] = "head",
                            ["Angles"] = Angle(-90, -180, 0),
                            ["AngleOffset"] = Angle(0, 0, 0),
                            ["BoneMerge"] = false,
                            ["Color"] = Vector(1, 1, 1),
                            ["Position"] = Vector(34.221923828125, -35.907081604004, 0.08203125),
                            ["ClassName"] = "model2",
                            ["Brightness"] = 1,
                            ["Hide"] = false,
                            ["NoCulling"] = false,
                            ["Scale"] = Vector(1, 1, 4.0999999046326),
                            ["LegacyTransform"] = false,
                            ["EditorExpand"] = true,
                            ["Size"] = 0.3,
                            ["ModelModifiers"] = "",
                            ["Translucent"] = false,
                            ["BlendMode"] = "",
                            ["EyeTargetUID"] = "",
                            ["Model"] = "models/props_wasteland/laundry_basket001.mdl",
                        },
                    },
                    [3] = {
                        ["children"] = {
                        },
                        ["self"] = {
                            ["Skin"] = 0,
                            ["UniqueID"] = "289830aeaa20f2f15823a4b130900707a9e86edc702b482ba1a86983265e5b06",
                            ["NoLighting"] = false,
                            ["AimPartName"] = "",
                            ["IgnoreZ"] = false,
                            ["AimPartUID"] = "",
                            ["Materials"] = "",
                            ["Name"] = "",
                            ["LevelOfDetail"] = 0,
                            ["NoTextureFiltering"] = false,
                            ["PositionOffset"] = Vector(0, 0, 0),
                            ["IsDisturbing"] = false,
                            ["EyeAngles"] = false,
                            ["DrawOrder"] = 0,
                            ["TargetEntityUID"] = "",
                            ["Alpha"] = 1,
                            ["Material"] = "",
                            ["Invert"] = false,
                            ["ForceObjUrl"] = false,
                            ["Bone"] = "head",
                            ["Angles"] = Angle(-90, -180, 0),
                            ["AngleOffset"] = Angle(0, 0, 0),
                            ["BoneMerge"] = false,
                            ["Color"] = Vector(1, 1, 1),
                            ["Position"] = Vector(34.222045898438, 35.189208984375, 0.08203125),
                            ["ClassName"] = "model2",
                            ["Brightness"] = 1,
                            ["Hide"] = false,
                            ["NoCulling"] = false,
                            ["Scale"] = Vector(1, 1, 4.0999999046326),
                            ["LegacyTransform"] = false,
                            ["EditorExpand"] = false,
                            ["Size"] = 0.3,
                            ["ModelModifiers"] = "",
                            ["Translucent"] = false,
                            ["BlendMode"] = "",
                            ["EyeTargetUID"] = "",
                            ["Model"] = "models/props_wasteland/laundry_basket001.mdl",
                        },
                    },
                    [4] = {
                        ["children"] = {
                        },
                        ["self"] = {
                            ["Skin"] = 0,
                            ["UniqueID"] = "0cce652777f6b1ce82e2bdf5afb63d41a2290633caa9b0a5c8c5d56779e360b5",
                            ["NoLighting"] = false,
                            ["AimPartName"] = "",
                            ["IgnoreZ"] = false,
                            ["AimPartUID"] = "",
                            ["Materials"] = "",
                            ["Name"] = "",
                            ["LevelOfDetail"] = 0,
                            ["NoTextureFiltering"] = false,
                            ["PositionOffset"] = Vector(0, 0, 0),
                            ["IsDisturbing"] = false,
                            ["EyeAngles"] = false,
                            ["DrawOrder"] = 0,
                            ["TargetEntityUID"] = "",
                            ["Alpha"] = 1,
                            ["Material"] = "",
                            ["Invert"] = false,
                            ["ForceObjUrl"] = false,
                            ["Bone"] = "head",
                            ["Angles"] = Angle(90, -90, 0),
                            ["AngleOffset"] = Angle(0, 0, 0),
                            ["BoneMerge"] = false,
                            ["Color"] = Vector(1, 1, 1),
                            ["Position"] = Vector(36, -20.173385620117, -0.384765625),
                            ["ClassName"] = "model2",
                            ["Brightness"] = 1,
                            ["Hide"] = false,
                            ["NoCulling"] = false,
                            ["Scale"] = Vector(1, 1, 1),
                            ["LegacyTransform"] = false,
                            ["EditorExpand"] = false,
                            ["Size"] = 1,
                            ["ModelModifiers"] = "",
                            ["Translucent"] = false,
                            ["BlendMode"] = "",
                            ["EyeTargetUID"] = "",
                            ["Model"] = "models/props_c17/metalladder002b.mdl",
                        },
                    },
                },
                ["self"] = {
                    ["DrawOrder"] = 0,
                    ["UniqueID"] = "639907eb71c6a4e5b83404fe6e112db77dd571d48baa909b8678723a8732fd45",
                    ["Hide"] = false,
                    ["TargetEntityUID"] = "",
                    ["EditorExpand"] = true,
                    ["OwnerName"] = "self",
                    ["IsDisturbing"] = false,
                    ["Name"] = "visual",
                    ["Duplicate"] = false,
                    ["ClassName"] = "group",
                },
            },
        },
        ["self"] = {
            ["DrawOrder"] = 0,
            ["UniqueID"] = "2df1884764e8af4ae8f09a26cd8d0e6014d3dfbeafff07af6a44f124a28acb6d",
            ["Hide"] = false,
            ["TargetEntityUID"] = "",
            ["EditorExpand"] = true,
            ["OwnerName"] = "89",
            ["IsDisturbing"] = false,
            ["Name"] = "missile_launcher",
            ["Duplicate"] = false,
            ["ClassName"] = "group",
        },
    }    
}