dmgsystem = {}

-- Damage type aliases
DMGSYS_TYPE_EXPLOSIVE = DMG_BLAST
DMGSYS_TYPE_AP = DMG_SNIPER
DMGSYS_TYPE_SHOTGUN = DMG_BUCKSHOT
DMGSYS_TYPE_BULLET = DMG_BULLET
DMGSYS_TYPE_ENERGY = DMG_PLASMA
DMGSYS_TYPE_PHYSICS = DMG_CRUSH